pages:
  stage: deploy
  script:
    - mkdir -p public
    - tar --exclude='.git' --exclude='.gitlab-ci.yml' --exclude='public' -cf site.tar .
    - tar -xf site.tar -C public
    - rm site.tar
  artifacts:
    paths:
      - public
  only:
    - main